import { useState, useEffect } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { diagnosticAPI } from "../services/api";
import "../assets/styles/assessmentResult.css";
import "../assets/styles/components.css";

export default function AssessmentResultPage() {
  const navigate = useNavigate();
  const location = useLocation();
  const state = location.state || {};

  const diseaseName = state.diseaseName || "Unknown diagnosis";
  const sourceType = state.source || "ai";
  const answers = state.answers || [];

  const [diseaseDetails, setDiseaseDetails] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [savingError, setSavingError] = useState("");

  useEffect(() => {
    if (!state.diseaseName) {
      return;
    }

    setLoading(true);
    setError("");

    diagnosticAPI
      .getDiseaseDetails(state.diseaseName)
      .then((response) => {
        setDiseaseDetails(response.data);
      })
      .catch((err) => {
        setError(err.response?.data || "Unable to load disease details.");
      })
      .finally(() => {
        setLoading(false);
      });
  }, [diseaseName]);

  const handleSaveResult = async () => {
    setSaving(true);
    setSavingError("");

    try {
      // Validate we have a result ID
      if (!state.diagnosticResultId || state.diagnosticResultId === 0) {
        setSavingError("Diagnostic result not available. Please restart assessment.");
        setSaving(false);
        return;
      }

      // Get answers from state or session storage
      const answersToSave = answers.length > 0 
        ? answers 
        : sessionStorage.getItem('diagnosticAnswers') 
          ? JSON.parse(sessionStorage.getItem('diagnosticAnswers'))
          : [];

      if (answersToSave.length === 0) {
        setSavingError("No answers to save. Please restart assessment.");
        setSaving(false);
        return;
      }

      const savePayload = {
        diagnosticResultId: state.diagnosticResultId,
        answers: answersToSave.map((ans) => ({
          questionText: ans.questionText || "",
          answer: ans.answer || "",
        })),
      };

      console.log("Saving diagnostic result with answers:", savePayload);

      const response = await diagnosticAPI.saveAnswers(savePayload);
      if (response.data?.success) {
        // Clear session storage after successful save
        sessionStorage.removeItem('diagnosticAnswers');
        setSaved(true);
        console.log("Answers saved successfully");
      } else {
        setSavingError(response.data?.message || "Failed to save answers.");
      }
    } catch (err) {
      console.error("Error saving answers:", err);
      setSavingError(err.response?.data?.message || err.message || "Failed to save result.");
    } finally {
      setSaving(false);
    }
  };

  const diagnosisLabel = diseaseDetails?.diseaseName || diseaseName;
  const description = diseaseDetails?.description || "No disease information available.";
  const nextSteps = diseaseDetails?.careInstructions
    ? diseaseDetails.careInstructions
        .split(".")
        .map((item) => item.trim())
        .filter(Boolean)
    : [];
  const confidenceValue = sourceType === "expert" ? "-" : state.confidence || "-";
  const metricWidth = sourceType === "expert" ? "0%" : `${state.confidence || 0}%`;
  const badgeText = sourceType === "expert" ? "Expert System" : "Verified AI";

  return (
    <div className="result-page">
      <Navbar />
      {/* <section className="result-disclaimer">
        <div className="disclaimer-card">
          <h3 className="disclaimer-title">Medical Disclaimer</h3>
            <p className="disclaimer-text">
            This assessment is generated by an AI-based system and is intended for informational purposes only. 
            It does not constitute a medical diagnosis or professional medical advice.
            </p>
            <p className="disclaimer-text">
            Always consult a qualified healthcare provider or dermatologist for an accurate diagnosis and treatment plan.
            Do not disregard professional medical advice based on this result.
            </p>
        </div>
      </section> */}
      <main className="result-body">
        <div className="result-header-row">
          <div>
            <div className="result-eyebrow">Clinical Analysis Report</div>
            <h1 className="result-title">Assessment Complete</h1>
          </div>

          <div className="result-header-actions">
            <button
              className="result-btn result-btn-ghost"
              type="button"
              onClick={() => window.print()}
              id="result-download-pdf"
            >
              Download PDF
            </button>
            <button
              className="result-btn result-btn-success"
              type="button"
              onClick={handleSaveResult}
              disabled={saving || saved}
              id="result-save-btn"
              style={{ opacity: saving || saved ? 0.7 : 1, cursor: saving || saved ? "not-allowed" : "pointer" }}
            >
              {saved ? "✓ Saved" : saving ? "Saving..." : "Save Result"}
            </button>
            <button
              className="result-btn result-btn-primary"
              type="button"
              onClick={() => navigate("/assistant")}
              id="result-consult-specialist"
            >
              Ask about my result
            </button>
          </div>
        </div>

        {loading && <div className="info-banner">Loading disease details…</div>}
        {error && <div className="error-banner">{error}</div>}
        {savingError && <div className="error-banner">{savingError}</div>}

        <section className="result-grid">
          {/* Left — Diagnosis */}
          <div className="result-card">
            <div className="result-card-top">
              <div>
                <div className="result-card-kicker">Primary Diagnosis</div>
                <div className="result-diagnosis-row">
                  <div className="result-diagnosis">{diagnosisLabel}</div>
                  <span className="badge badge-success">{badgeText}</span>
                </div>
              </div>
            </div>

            <div className="result-metric">
              <div className="result-metric-label">AI Confidence Score</div>
              <div className="result-metric-row">
                <div className="result-metric-bar">
                  <div className="result-metric-fill" style={{ width: metricWidth }} />
                </div>
                <div className="result-metric-value">{confidenceValue}</div>
              </div>
            </div>

            <div className="result-image-card" aria-label="Dermatology close-up illustration">
              <div className="result-image-overlay" />
              {sourceType === "expert" ? (
                <div className="result-no-photo" style={{ padding: "2rem 1rem", textAlign: "center", color: "#fff", fontWeight: 700 }}>
                  No photo
                </div>
              ) : (
                <>
                  <svg
                    className="result-image-lines"
                    viewBox="0 0 240 140"
                    xmlns="http://www.w3.org/2000/svg"
                    aria-hidden="true"
                  >
                    <defs>
                      <linearGradient id="skinGrad" x1="0" y1="0" x2="1" y2="1">
                        <stop offset="0" stopColor="rgba(255,255,255,0.15)" />
                        <stop offset="1" stopColor="rgba(255,255,255,0)" />
                      </linearGradient>
                    </defs>
                    <rect x="0" y="0" width="240" height="140" fill="url(#skinGrad)" />
                    <path
                      d="M-10 105 C 40 75, 80 110, 130 85 C 170 65, 210 95, 260 60"
                      stroke="rgba(255,255,255,0.45)"
                      strokeWidth="2.4"
                      fill="none"
                    />
                    <path
                      d="M-10 120 C 50 95, 90 130, 145 102 C 185 82, 215 110, 260 80"
                      stroke="rgba(255,255,255,0.22)"
                      strokeWidth="2"
                      fill="none"
                    />
                  </svg>
                  <div className="result-image-caption">Microscopic texture analysis</div>
                </>
              )}
            </div>

            <div className="result-pill-grid">
              <div className="result-pill">
                <div className="result-pill-label">Severity</div>
                <div className="result-pill-value">{diseaseDetails?.severityLevel || "Unknown"}</div>
              </div>
              <div className="result-pill">
                <div className="result-pill-label">Source</div>
                <div className="result-pill-value">{sourceType === "expert" ? "Expert System" : "AI Model"}</div>
              </div>
            </div>
          </div>

          {/* Right — Details */}
          <div className="result-right">
            <div className="result-card">
              <div className="result-section-title">About {diagnosisLabel}</div>
              <p className="result-paragraph">{description}</p>

            </div>

            <div className="result-card">
              <div className="result-section-title">Care Instructions </div>

              {nextSteps.length > 0 ? (
                nextSteps.map((step, index) => (
                  <button
                    key={index}
                    className="nextstep"
                    type="button"
                    onClick={() => navigate("/assistant")}
                    id={`nextstep-${index + 1}`}
                  >
                    <span className="nextstep-num">{index + 1}</span>
                    <span className="nextstep-main">
                      <span className="nextstep-title">{step}</span>
                      <span className="nextstep-desc">Review this guidance with a clinician if needed.</span>
                    </span>
                    <span className="nextstep-arrow" aria-hidden="true">
                      ›
                    </span>
                  </button>
                ))
              ) : (
                <button className="nextstep" type="button" onClick={() => navigate("/assistant")}> 
                  <span className="nextstep-num">1</span>
                  <span className="nextstep-main">
                    <span className="nextstep-title">Continue monitoring symptoms</span>
                    <span className="nextstep-desc">Return to the assistant for further guidance.</span>
                  </span>
                  <span className="nextstep-arrow" aria-hidden="true">›</span>
                </button>
              )}
            </div>
          </div>
        </section>
        
      </main>
      <Footer />
    </div>
  ); 
}
