name: al_derma
description: AI-powered clinical skin disease detection assistant
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Navigation
  go_router: ^13.0.0

  # UI
  google_fonts: ^6.1.0
  animate_do: ^3.1.2
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1

  # Image
  image_picker: ^1.0.7

  # Utils
  intl: ^0.19.0

  # HTTP & Storage
  http: ^1.2.0
  dio: ^5.4.3
  shared_preferences: ^2.2.3


  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # إضافة الـ Assets (اختياري)
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/animations/